# Generated by Django 5.1.3 on 2024-11-13 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FastMeow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios', to='FastMeow.ticket'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes', to='FastMeow.ticket'),
        ),
        migrations.CreateModel(
            name='TicketsArchivados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.TextField()),
                ('numero', models.IntegerField()),
                ('id_compuesto', models.CharField(editable=False, max_length=50, unique=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FastMeow.categoriaproblema')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FastMeow.cliente')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FastMeow.estado')),
                ('prioridad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FastMeow.prioridad')),
            ],
        ),
    ]
