# Generated by Django 5.1.1 on 2024-11-20 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FastMeow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='ticket_archivado',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='ticket_archivado',
        ),
    ]
