# Generated by Django 5.1.1 on 2024-11-20 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FastMeow', '0002_remove_comentario_ticket_archivado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='ticket_archivado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_archivados', to='FastMeow.ticketsarchivados'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='ticket_archivado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes_archivadas', to='FastMeow.ticketsarchivados'),
        ),
    ]
