# Generated by Django 5.1.3 on 2024-11-13 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FastMeow', '0002_alter_comentario_ticket_alter_imagen_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='ticket_archivado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_archivados', to='FastMeow.ticketsarchivados'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='ticket_archivado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes_archivadas', to='FastMeow.ticketsarchivados'),
        ),
    ]
