# Generated by Django 5.1.3 on 2024-11-14 04:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FastMeow', '0003_comentario_ticket_archivado_imagen_ticket_archivado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='fecha_subida',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='numero',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id_compuesto',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
